export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';

export const GET_ALL_BRAND = 'GET_ALL_BRAND';
export const CREATE_BRAND = 'CREATE_BRAND';

export const CREATE_SUB_CATEGORY = 'CREATE_SUB_CATEGORY';
export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';

export const GET_ERROR = 'GET_ERROR';
