export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY';

export const GET_ALL_BRAND = 'GET_ALL_BRAND';
export const CREATE_BRAND = 'CREATE_BRAND';
export const GET_ONE_BRAND = 'GET_ONE_BRAND';

export const CREATE_SUB_CATEGORY = 'CREATE_SUB_CATEGORY';
export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_RESULTS_PRODUCTS = 'GET_RESULTS_PRODUCTS';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';
export const GET_PRODUCT_LIKE = 'GET_PRODUCT_LIKE';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const GET_ERROR = 'GET_ERROR';
